export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENT = 'GET_CLIENT'
export const GET_DOCTORS = 'GET_DOCTORS'
export const GET_DOCTOR = 'GET_DOCTOR'
export const RES_DATA = 'RES_DATA'
export const RES_ERRORS = 'RES_ERRORS'
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE'